@startuml class

interface IDownloadable{
    +download(): void

}

interface IPlayable{
    +playback(): void
}


abstract class LibraryItem {
  +void lendItem()
  +void returnItem()
}

class Book extends LibraryItem {

}
class EBook extends Book{

}

class Magazine extends LibraryItem{

}

class DVD extends LibraryItem{

}
EBook ..|> IDownloadable
DVD ..|> IPlayable
@enduml
